export const GET_PRODUCTS = "GET_PRODUCTS";

export const GET_PRODUCTS_ASYNC = "GET_PRODUCTS_ASYNC";

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";

export const GET_PRODUCTS_FROM_CART = "GET_PRODUCTS_FROM_CART";

export const REMOVE_SINGLE_PRODUCT = "REMOVE_SINGLE_PRODUCT";
